eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-b:
  baseUrl: localhost
server:
  port: 8100
spring:
  application:
    name: microservice-a